# Site settings
title: eridem.net
author: "Miguel Ángel Domínguez Coloma"
copyright: "Eridem AB"
header-img: img/home-bg.jpg
email: m@eridem.net
copyright_name: Eridem
description: "miguel ángel domínguez coloma´s blog"
baseurl: ""
url: "http://eridem.net"

# Social
twitter_username: eridemnet
github_username:  eridem
facebook_username:  
npm_username: eridem
linkedin_username: eridem
email_username: info@eridem.net

# Google Analytics
google_tracking_id: UA-51139284-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 39
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
