# Site settings
title: eridem ab
header-img: img/home-bg.jpg
email: m@eridem.net
copyright_name: Eridem
description: "miguel ángel domínguez coloma´s blog"
baseurl: ""
url: "http://eridem.net"
twitter_username: eridemnet
github_username:  eridem
facebook_username:  
email_username: m@eridem.net

# Google Analytics
google_tracking_id: UA-51139284-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 11
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
